version: 2.1
orbs:
 node: circleci/node@5.0.2
jobs:
  run_tests:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo git clone https://github.com/sstephenson/bats.git ~/bats
      - run: pushd ~/bats && sudo bash install.sh /usr/local && popd

      - run: ln -s ~/repo ~/$CIRCLE_PROJECT_REPONAME
      - node/install-packages
      # - run: npm run commitlint-last-commit
      - run:
          command: npm run build
      - run:
          command: npm run test

  npm_publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: auth with npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: bash .circleci/npm-publish.sh

  build_docker_image:
    working_directory: ~/repo
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run: sh .circleci/docker-build.sh

workflows:
  version: 2
  test:
    jobs:
      - run_tests
  publish:
    jobs:
      - run_tests:
          filters: &filters-publish
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build_docker_image:
          requires:
            - run_tests
          filters:
            <<: *filters-publish
      - npm_publish:
          requires:
            - run_tests
          filters:
            <<: *filters-publish
